from app.models import db, Image, environment, SCHEMA
from sqlalchemy.sql import text

item_images =[
    Image(item_id=1, url=""),
    Image(item_id=1, url=""),
    Image(item_id=1, url=""),
    Image(item_id=1, url=""),
    Image(item_id=1, url=""),
    Image(item_id=1, url=""),
    Image(item_id=2, url=""),
    Image(item_id=2, url=""),
    Image(item_id=2, url=""),
    Image(item_id=2, url=""),
    Image(item_id=2, url=""),
    Image(item_id=2, url=""),
    Image(item_id=3, url=""),
    Image(item_id=3, url=""),
    Image(item_id=3, url=""),
    Image(item_id=3, url=""),
    Image(item_id=3, url=""),
    Image(item_id=3, url=""),
    Image(item_id=4, url=""),
    Image(item_id=4, url=""),
    Image(item_id=4, url=""),
    Image(item_id=4, url=""),
    Image(item_id=4, url=""),
    Image(item_id=4, url=""),
    Image(item_id=5, url=""),
    Image(item_id=5, url=""),
    Image(item_id=5, url=""),
    Image(item_id=5, url=""),
    Image(item_id=5, url=""),
    Image(item_id=5, url=""),
    Image(item_id=6, url=""),
    Image(item_id=6, url=""),
    Image(item_id=6, url=""),
    Image(item_id=6, url=""),
    Image(item_id=6, url=""),
    Image(item_id=6, url=""),
    Image(item_id=7, url=""),
    Image(item_id=7, url=""),
    Image(item_id=7, url=""),
    Image(item_id=7, url=""),
    Image(item_id=7, url=""),
    Image(item_id=7, url=""),
    Image(item_id=8, url=""),
    Image(item_id=8, url=""),
    Image(item_id=8, url=""),
    Image(item_id=8, url=""),
    Image(item_id=8, url=""),
    Image(item_id=8, url=""),
    Image(item_id=9, url=""),
    Image(item_id=9, url=""),
    Image(item_id=9, url=""),
    Image(item_id=9, url=""),
    Image(item_id=9, url=""),
    Image(item_id=9, url=""),
    Image(item_id=10, url=""),
    Image(item_id=10, url=""),
    Image(item_id=10, url=""),
    Image(item_id=10, url=""),
    Image(item_id=10, url=""),
    Image(item_id=10, url=""),
    Image(item_id=11, url=""),
    Image(item_id=11, url=""),
    Image(item_id=11, url=""),
    Image(item_id=11, url=""),
    Image(item_id=11, url=""),
    Image(item_id=11, url=""),
    Image(item_id=12, url=""),
    Image(item_id=12, url=""),
    Image(item_id=12, url=""),
    Image(item_id=12, url=""),
    Image(item_id=12, url=""),
    Image(item_id=12, url=""),
    Image(item_id=13, url=""),
    Image(item_id=13, url=""),
    Image(item_id=13, url=""),
    Image(item_id=13, url=""),
    Image(item_id=13, url=""),
    Image(item_id=13, url=""),
    Image(item_id=14, url=""),
    Image(item_id=14, url=""),
    Image(item_id=14, url=""),
    Image(item_id=14, url=""),
    Image(item_id=14, url=""),
    Image(item_id=14, url=""),
    Image(item_id=15, url=""),
    Image(item_id=15, url=""),
    Image(item_id=15, url=""),
    Image(item_id=15, url=""),
    Image(item_id=15, url=""),
    Image(item_id=15, url=""),
    Image(item_id=16, url=""),
    Image(item_id=16, url=""),
    Image(item_id=16, url=""),
    Image(item_id=16, url=""),
    Image(item_id=16, url=""),
    Image(item_id=16, url=""),
    Image(item_id=17, url=""),
    Image(item_id=17, url=""),
    Image(item_id=17, url=""),
    Image(item_id=17, url=""),
    Image(item_id=17, url=""),
    Image(item_id=17, url=""),
    Image(item_id=18, url=""),
    Image(item_id=18, url=""),
    Image(item_id=18, url=""),
    Image(item_id=18, url=""),
    Image(item_id=18, url=""),
    Image(item_id=18, url=""),
    Image(item_id=19, url=""),
    Image(item_id=19, url=""),
    Image(item_id=19, url=""),
    Image(item_id=19, url=""),
    Image(item_id=19, url=""),
    Image(item_id=19, url=""),
    Image(item_id=20, url=""),
    Image(item_id=20, url=""),
    Image(item_id=20, url=""),
    Image(item_id=20, url=""),
    Image(item_id=20, url=""),
    Image(item_id=20, url=""),
]

def seed_images():
    for image in item_images:
        db.session.add(image)
    db.session.commit()

def undo_images():
    if environment == "production":
        db.session.execute(
            f"TRUNCATE table {SCHEMA}.images RESTART IDENTITY CASCADE;")
    else:
        db.session.execute(text("DELETE FROM images"))
    db.session.commit()
